ins ={
'1': "The current stance is Pranamasana, also known as Prayer pose.\nGet ready for the next posture that is Hastauttanasana, a Raised arms pose \n,Instruction for Hastauttanasana are \n step1 \n	Breathing in, lift the arms up and bend back, keeping the biceps close to the ears. \n",
'2': "The current stance is Hastauttanasana, also known as Raised arms pose.\n Get ready for the next posture that is Hastapadasana ,a Standing forward bend \n Instruction for Hastapadasana are , step1 \nBreathing out, bend forward from the waist keeping the spine erect. \n step2\n As you exhale completely, bring the hands down to the floor beside the feet.",
'3': "The current stance is Hastapadasana also known as Standing forward bend.\n Get ready for the next posture that is, Ashwa Sanchalanasana , a Equestrian pose \nInstruction for Ashwa Sanchalanasana are \nstep1,\n	Breathing in, push your right leg back, as far back as possible.\nstep2,\n Bring the right knee to the floor and look up.\n",
'4': "The current stance is Ashwa Sanchalanasana also known as Equestrian pose.\n Get ready for the next posture that is, Dandasana , a Stick pose\n Instruction for Dandasana are\n step1,\n	As you breathe in, take the left leg back and bring the whole body in a straight line.\n",
'5': "The current stance is Dandasana also known as Stick pose.\n Get ready for the next posture that is, Ashtanga Namaskara , a salute with eight parts \n Instruction for Ashtanga Namaskara are\n step1,\n	Gently bring your knees down to the floor and exhale. \n step2,\nTake the hips back slightly, slide forward, rest your chest and chin on the floor. \n step3,\n	Raise your posterior a little bit. The two hands, two feet, two knees, chest and chin , eight parts of the body should touch the floor.\n",
'6': "The current stance is Ashtanga Namaskara also known as Salute with eight parts.\nGet ready for the next posture that is, Bhujangasana , a Cobra pose\n Instruction for Bhujangasana are\nstep1,\n	Place your palms flat on the ground directly under your shoulders. Bend your elbows straight back and hug them into your sides.\n step 2\n Inhale to lift your chest off the floor.",
'7': "The current stance is Bhujangasana also known as Cobra pose.\nGet ready for the next posture that is, Parwatasan , Downward facing dog pose\nInstruction for Parwatasan are \nstep1,\nBreathing out, lift the hips and the tailbone up to bring the body into an inverted V pose.\n",
'8': "The current stance is Parwatasan also known as Downward facing dog pose.\nGet ready for the next posture that is, Pranamasana , Prayer pose\nInstruction for Pranamasana are\nstep1,\n	Stand at the edge of your mat.\nstep2,\n	keep your feet together and balance your weight equally on both the feet. \nstep3,\n	Expand your chest and relax your shoulders. \nstep4,\n	As you breathe in, lift both arms up from the sides, and as you exhale, bring your palms together in front of the chest in prayer position.\n"
}

print(ins['1'])
